print ("hello M.6/14")
print ("You can checking my proflie when you are have begin with my simple stories in my life")
print ("My name is")
print ("Athiphat Aphimongkol")
age = "17 years old"
print (age)
print ("31/01/2005")    
print ("Blood group :")
print ("A") 
print ("My nickname is :")
print ("Treetree")
print ("Adress :")
print ("117 M.1 S.nartmontasevi 11/2 T.Samet A.Muang Chonburi 20000")
print ("My favorite subject :")
print ("Japanese,english,history")
print ("My favourite food")
print ("pizza,steak,spagetthi")